[Router]: Info: Start to listen on port 31244
[Router]: Info: Client 127.0.0.1:53212 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53212 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53216 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53217 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53219 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53213 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53209 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53218 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53215 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53211 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53214 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53224 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53210 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53223 connected, with message ClientRequestServer
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Info: Process started
[Router]: Info: Client 127.0.0.1:53208 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53222 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53225 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53220 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53221 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53227 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53226 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53228 connected, with message ClientRequestServer
[Router]: Info: Client 127.0.0.1:53229 connected, with message ClientRequestServer
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Info: Process started
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Info: Process started
[Router]: Info: Client 127.0.0.1:53235 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53236 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53237 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53239 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53238 connected, with message ServerStarted
[Router]: Info: Client 127.0.0.1:53240 connected, with message ServerStarted
[Router]: Info: Client 127.0.0.1:53241 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53243 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53242 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53244 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53245 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53246 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53247 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53248 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53249 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53250 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53251 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53253 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53252 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53254 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53255 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53256 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53257 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53258 connected, with message ServiceProvideServer
[Router]: Info: Client 127.0.0.1:53211 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53262 connected, with message ServerStarted
[Router]: Info: Client 127.0.0.1:53263 connected, with message ServerStarted
[Router]: Error: Could not find a matching server Guid
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error: 
[Router]: Error: Could not find a matching server Guid
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error: Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 82
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Router]: Info: Client 127.0.0.1:53209 disconnected with exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: GameStudio mode started!
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: GameStudio mode started!
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: Router: Unknown message: 385
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: Client connected
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: Client connected
[SiliconStudio.Paradox.EffectCompilerServer:14004]: Info: 
[Router]: Info: Client 127.0.0.1:53212 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53218 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53214 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53224 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53223 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53222 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53208 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53221 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53229 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53226 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53225 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53228 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53220 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53227 disconnected with exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[Router]: Info: Client 127.0.0.1:53217 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53215 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53219 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53216 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53213 disconnected with exception: Server could not connect back in time
[Router]: Info: Client 127.0.0.1:53210 disconnected with exception: Server could not connect back in time
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    --- End of inner exception stack trace ---
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadAllAsync>d__0.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 16
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:15900]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:6200]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:15716]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at SiliconStudio.Paradox.Engine.Network.SocketExtensions.<ReadInt16Async>d__4.MoveNext() in C:\Dev\Paradox-2\sources\engine\SiliconStudio.Paradox.Engine\Engine\Network\SocketExtensions.cs:line 46
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7044]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at SiliconStudio.Paradox.ConnectionRouter.RouterServiceServer.<>c__DisplayClass5_0.<<CreateSocketContext>b__0>d.MoveNext() in C:\Dev\Paradox-2\sources\tools\SiliconStudio.Paradox.ConnectionRouter\RouterServiceServer.cs:line 53
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: --- End of stack trace from previous location where exception was thrown ---
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__5(Object state)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:3496]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:9484]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:17624]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:15936]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:6052]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:17328]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:15792]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:13688]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:3040]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:12832]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:18132]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:1256]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:7856]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:16004]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:12836]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:3456]: Error: 
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Info: 
[SiliconStudio.Paradox.EffectCompilerServer:9360]: Error: 
